@echo off
rem Autogenerated by LiteX
yosys -q -l top.rpt top.ys || exit /b
arachne-pnr -q -d 8k -P cm81 -p top.pcf top.blif -o top.txt || exit /b
icetime -P cm81 -d lp8k -c 16.0 -t -p top.pcf -r top.tim top.txt || exit /b
icepack -s top.txt top.bin || exit /b
